### ISSUE TITLE
Не собирается apk файл

### ISSUE THREAD

**Issue by tellts** [Helltar/AMPASIDE#2]
Пробую собрать Space из проекта примера, приложенного к программе. Не могу найти Space.apk. В какой папке его искать, если программа установлена по пути C:\AMPASIDE\bin (версия из ampaside-1.0.3_windows.zip)?

ant.log содержит строку:
Buildfile: C:\AMPASIDE\bin\tools\android\build.Space.xml

`Microsoft Windows [Version 10.0.19044.1766]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\admin>ant -version
Apache Ant(TM) version 1.10.12 compiled on October 13 2021

C:\Users\admin>javac -version
javac 18

C:\Users\admin>java -version
java version "18" 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)

C:\Users\admin>`

**Comment by Helltar** [comment]
Привет, как раз работаю над этим, в последних коммитах уже пофикшено, за день-два соберу релиз.

**Comment by Helltar** [comment]
Исправил: https://github.com/Helltar/AMPASIDE/releases/tag/v1.1.5
Нужно установить **JDK 8**: https://github.com/Helltar/AMPASIDE/blob/master/help/install_windows.md

**Comment by tellts** [comment]
Установил рекомендуемую вами JDK 8 и скачал новый дистрибутив. Хотя пишет, что проект успешно собран, папка C:\AMPASIDE\examples\Cubes\bin\apk пустая.

ant.log
`Apache Ant(TM) version 1.10.12 compiled on October 13 2021
Buildfile: C:\AMPASIDE\tmp\build.Cubes.xml
`

**Comment by Helltar** [comment]
_JAVA_HOME_ новый прописался? Что показывает _java -version_ и _javac -version_ в ком. строке Windows?
Возможно надо перезагрузится после установки нового JDK.

**Comment by Helltar** [comment]
Посмотрел еще раз, запустил новый релиз начисто, все собрало:

![screenshot_23062022_114251](https://user-images.githubusercontent.com/6628997/175257713-e79ee54d-a088-44bf-ba58-739e6ec6cfb7.png)

![screenshot_23062022_114547](https://user-images.githubusercontent.com/6628997/175257745-608aa82c-8428-4676-b8ae-a972e685dcab.png)

![screenshot_23062022_114530](https://user-images.githubusercontent.com/6628997/175257758-290471f9-7e0b-492d-82bc-c04fd7eb3cc7.png)

**Comment by tellts** [comment]
Да, изначально делал неправильно, не отметив при установке OpenJDK пункт  JAVA_HOME. Сейчас сделал по новой, только по-прежнему не работает после перезагрузки.

Сравните, пожалуйста данные в этом окне и сообщите, если увидите ошибку или сделайте скриншот, чтобы сам посмотрел. Сюда в Виндовс 10 можно попасть, если счелкнуть правой кнопкой мыши по иконке "Этот компьютер", выбрать в самом низу Свойства и в открывшемся окне найти "Дополнительные параметры системы" и там в самом низу кнопка "Переменные среды". Скриншот делал после перезагрузки.
https://imgbox.com/707PpUEl

В консоли у нас строки совпадают
https://imgbox.com/9o0uLOfQ

Во время установки отметил сейчас JAVA_HOME
https://imgbox.com/phD3cOxt

Нижний пункт, который наверное связан с реестром, не отмечал
https://imgbox.com/hTU0fYYT

**Comment by Helltar** [comment]
_ANT_HOME_ и _%ANT_HOME%\bin_ добавлены? На скриншотах не вижу, хотя если в консоли работает то наверно добавлены, если нет, нужно добавить:

- https://ant.apache.org/manual/install.htm

![screenshot_23062022_150614](https://user-images.githubusercontent.com/6628997/175296002-434df5f5-dfd1-4a42-9e07-cae69e651d59.png)

![screenshot_23062022_150700](https://user-images.githubusercontent.com/6628997/175296012-24c4b280-b4d8-400d-8946-11591fa1efb4.png)

**Comment by Helltar** [comment]
Меня немного пользователь _admin_ смущает, я бы попробовал еще удалить это:

![707PpUEl_o (1)](https://user-images.githubusercontent.com/6628997/175297511-788ffa5d-45f0-4868-81f7-189258b960fa.png)

**Comment by tellts** [comment]
Сейчас буду делать правильные пути для Apache Ant. Пока что прикладываю на всякий случай скриншот.
https://imgbox.com/4WswdrrM

**Comment by tellts** [comment]
А ANT_HOME на папку с чем должна указывать? На саму директорию, в которой папка bin?

**Comment by Helltar** [comment]
Да, _ANT_HOME_ на родительскую где bin: _C:\apache-ant-1.10.12_ и отдельно добавить в Path _%ANT_HOME%\bin_

**Comment by tellts** [comment]
Удалил лишние строки, как Вы предложили и после перезагрузки заработало. Сейчас сделаю инструкцию по установке и напишу на форуме программистов. После этого возможно ещё кто-то скачает программу. Ссылку на тему на форуме сообщу Вам сюда.

**Comment by tellts** [comment]
https://www.cyberforum.ru/pascal/thread3002524.html
