### ISSUE TITLE
Эмулятор смартфона

### ISSUE THREAD

**Issue by tellts** [Helltar/AMPASIDE#3]
На картинке справа изображен смартфон. Не пойму, как эмулятор в таком виде запускается?
Картинка:
https://camo.githubusercontent.com/98bb2c449799c0489465c4c37b3ba04b364be58fcb83b18ddb20c9c9f81a64fd/68747470733a2f2f68656c6c7461722e636f6d2f70726f6a656374732f616d7061736964652f73637265656e73686f74732f73637265656e73686f745f32333036323032325f3134323535302e706e67

**Comment by Helltar** [comment]
Встроенный эмулятор запускает только .jar (JavaME), на скрине андроид эмулятор из Android Studio.

- https://www.youtube.com/watch?v=YKPKqdwdn3I

Добавлять его в релизы конечно же безумно, > 500 mb.

**Comment by tellts** [comment]
А если установить Android Studio, то как быстро открывать apk через него для запуска в эмуляторе? Просто не работал в нём и не знаю, куда там нажимать надо будет.

**Comment by tellts** [comment]
Нельзя ли эмулятор поставить отдельно без Андроид Студии?

**Comment by Helltar** [comment]
Не обязательно использовать эмулятор из андроид студии, можно любой другой андроид эмулятор для windows.

А эмулятор идущий с андроид студией после установки можно запускать отдельно, апк устанавливаются просто перетаскиванием на него (видео по ссылке выше).

**Comment by tellts** [comment]
Благодарю за ответы. А J2ME устройства сейчас выпускаются? Имею в виду, программы пишутся только для старых телефонов (возможно прикуплю такой, если попадется дешево хороший со сменной батареей, которую можно купить) или на современных кнопочных по-прежнему встречается и возможно другая техника тоже выпускается?

**Comment by Helltar** [comment]
Не скажу, ибо не имел дело со современными кнопочными, нужно уже смотреть характеристики при покупке.

Но из б/у это почти все, у одной только нокии 1.5 млрд. на S40.
